name: Documentation

on: [ push ]

jobs:
  BuildTheDocs:
    name: Run BuildTheDocs and publish to GH-Pages
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build pyVHDLModel/doc
      run: |
        docker build -t vhdl/doc - <<-EOF
        FROM btdi/sphinx:featured
        RUN apk add -U --no-cache graphviz
        EOF

    - uses: buildthedocs/btd@v0
      with:
        token: ${{ github.token }}

    - uses: actions/upload-artifact@master
      with:
        name: doc
        path: doc/_build/html
